### ISSUE TITLE
Can't add Celo Safe Owner

### ISSUE THREAD

**Issue by zmarks215** [celo-org/web-core#8]
Hi,
I'm trying to add an owner to our multisig Celo SAFE. 
I don't see the option/button to add a Safe owner the way i do in gnosis safe. My cofounder Cheng, also one of the owners, does not see that button. any ideas what's going on?

It's for the celo-jia wallet: 
mainnet:0xD3CCe1eC5a3981B27bD998f33A7eafdD27Ad2dF4

i am user: mainnet:0xB40a6D4C73766F769Cb3393B62488Fd57db04AA4

my wallet is connected when i'm trying to transact. 

![photo_2022-12-12_16-46-34](https://user-images.githubusercontent.com/9206140/207198841-58c5e9d5-26f1-4c72-83b6-5c1cbaced0e6.jpg)

**Comment by dckesler** [comment]
Hello! Thanks for making an issue. I'm looking into this today.

**Comment by zmarks215** [comment]
Thanks Daniel!

**Comment by nicolasbrugneaux** [comment]
Hello zmarks215! :) From your screenshot it seems your connected metamask isn't using celo mainnet. Can you make sure you click the "Switch to MAINNET" (visible top right of the screenshot) and see if you have access to the add owners button? See my screenshots as an example of the expected behaviour.
<img width="1430" alt="Screenshot 2022-12-13 at 19 11 27" src="https://user-images.githubusercontent.com/3650621/207412129-5ead1648-8683-44e0-8426-24b7e8a34dbd.png">
<img width="1511" alt="Screenshot 2022-12-13 at 19 11 34" src="https://user-images.githubusercontent.com/3650621/207412132-353f9df2-1403-48c6-b718-97f826bcf87c.png">
<img width="1444" alt="Screenshot 2022-12-13 at 19 11 40" src="https://user-images.githubusercontent.com/3650621/207412133-fd157465-4a57-449d-9943-ec6a50b80956.png">

**Comment by nicolasbrugneaux** [comment]
Marking this as solved, feel free to reopen if you still can't add owners

**Comment by zmarks215** [comment]
Thanks so much!
